spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: chensheng
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
   context-path: /sell
   port: 8081
#logging:
#  path: /var/log/tomcat/
#  pattern:
#    console: "%d - %msg%n"
#    file: /var/log/tomcat/sell.log
#    level: debug

